### ISSUE TITLE
finish 추가건

### ISSUE THREAD

**Issue by Redcompany** [kimyudoo/KOPOProject#4]
1. choyoungdo_Activity
2. GwangWon_Activity
3. kimjihyunActivity
4. namsgActivity

**Comment by ernie-cho** [comment]
choyoungdo_Activity 
finish 추가 완료
67ad773

**Comment by rlawlgus** [comment]
kimjihyunActivity finish(); 수정 완료하였습니다.

**Comment by MisterSGW** [comment]
GwangWon 수정완료.

**Comment by junwoo0830** [comment]
모두 수정 되었습니다.
